system:
  config:
    deployment-version: LOCAL
    auth-url: http://localhost.localstack.cloud:4566/_aws/cognito-idp
    user-pool-id: ap-southeast-1_localpoolid
    sns-topic-arn: arn:aws:sns:ap-southeast-1:000000000000:invoicer-sns-topic

logging:
  level:
    tech.sangdang.invoicer.config.AwsCognitoAdapterConfig: trace

spring:
  application:
    name: invoicer
  web:
    error:
      include-message: always
  cloud:
    aws:
      region:
        static: ap-southeast-1
      endpoint: http://localhost.localstack.cloud:4566
      dynamodb:
        endpoint: http://localhost.localstack.cloud:4566
  boot:
    admin:
      client:
        enabled: false # Disabled for local development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost.localstack.cloud:4566/ap-southeast-1_localpoolid}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    persist-authorization: true
    filter: true
    display-request-duration: on
    syntax-highlight:
      activated: true
      theme: obsidian
    doc-expansion: none
  api-docs:
    enabled: true
aws:
  s3:
    bucket-name: invoicer-inbound
    permastore-bucket-name: invoicer-permastore
    default-presigned-upload-ttl-mins: 10
    default-presigned-download-ttl-mins: 10