system:
  config:
    deployment-version: LOCAL

logging:
  level:
    tech.sangdang.invoicer.config.AwsCognitoAdapterConfig: trace

spring:
  application:
    name: invoicer
  web:
    error:
      include-message: always
  cloud:
    aws:
      region:
        static: ap-southeast-1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:https://placeholder.com}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    persist-authorization: true
    filter: true
    display-request-duration: on
    syntax-highlight:
      activated: true
      theme: obsidian
    doc-expansion: none
    oauth:
      client-id: ${SWAGGER_UI_OAUTH_CLIENT_ID}
      client-secret: ${SWAGGER_UI_OAUTH_CLIENT_SECRET}
      scopes:
        - email
        - openid
        - phone
        - profile
        - aws.cognito.signin.user.admin
  api-docs:
    enabled: true
aws:
  s3:
    bucket-name: ${S3_INBOUND_BUCKET_NAME:invoicer-inbound}
    default-presigned-upload-ttl-mins: 10