/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserInvoiceRouteImport } from './routes/user/invoice'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as AdminInvoiceRouteImport } from './routes/admin/invoice'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as UserInvoiceIndexRouteImport } from './routes/user/invoice/index'
import { Route as AdminInvoiceIndexRouteImport } from './routes/admin/invoice/index'
import { Route as AdminAccountIndexRouteImport } from './routes/admin/account/index'
import { Route as UserInvoiceInvoiceIdRouteImport } from './routes/user/invoice/$invoiceId'
import { Route as AdminInvoiceNewRouteImport } from './routes/admin/invoice/new'
import { Route as AdminInvoiceInvoiceIdRouteImport } from './routes/admin/invoice/$invoiceId'
import { Route as AdminAccountAccountIdRouteImport } from './routes/admin/account/$accountId'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserInvoiceRoute = UserInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const AdminInvoiceRoute = AdminInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const UserInvoiceIndexRoute = UserInvoiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserInvoiceRoute,
} as any)
const AdminInvoiceIndexRoute = AdminInvoiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminInvoiceRoute,
} as any)
const AdminAccountIndexRoute = AdminAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAccountRoute,
} as any)
const UserInvoiceInvoiceIdRoute = UserInvoiceInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => UserInvoiceRoute,
} as any)
const AdminInvoiceNewRoute = AdminInvoiceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminInvoiceRoute,
} as any)
const AdminInvoiceInvoiceIdRoute = AdminInvoiceInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AdminInvoiceRoute,
} as any)
const AdminAccountAccountIdRoute = AdminAccountAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AdminAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/account': typeof AdminAccountRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoice': typeof AdminInvoiceRouteWithChildren
  '/user/dashboard': typeof UserDashboardRoute
  '/user/invoice': typeof UserInvoiceRouteWithChildren
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/admin/invoice/$invoiceId': typeof AdminInvoiceInvoiceIdRoute
  '/admin/invoice/new': typeof AdminInvoiceNewRoute
  '/user/invoice/$invoiceId': typeof UserInvoiceInvoiceIdRoute
  '/admin/account/': typeof AdminAccountIndexRoute
  '/admin/invoice/': typeof AdminInvoiceIndexRoute
  '/user/invoice/': typeof UserInvoiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/admin/invoice/$invoiceId': typeof AdminInvoiceInvoiceIdRoute
  '/admin/invoice/new': typeof AdminInvoiceNewRoute
  '/user/invoice/$invoiceId': typeof UserInvoiceInvoiceIdRoute
  '/admin/account': typeof AdminAccountIndexRoute
  '/admin/invoice': typeof AdminInvoiceIndexRoute
  '/user/invoice': typeof UserInvoiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/account': typeof AdminAccountRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoice': typeof AdminInvoiceRouteWithChildren
  '/user/dashboard': typeof UserDashboardRoute
  '/user/invoice': typeof UserInvoiceRouteWithChildren
  '/admin/account/$accountId': typeof AdminAccountAccountIdRoute
  '/admin/invoice/$invoiceId': typeof AdminInvoiceInvoiceIdRoute
  '/admin/invoice/new': typeof AdminInvoiceNewRoute
  '/user/invoice/$invoiceId': typeof UserInvoiceInvoiceIdRoute
  '/admin/account/': typeof AdminAccountIndexRoute
  '/admin/invoice/': typeof AdminInvoiceIndexRoute
  '/user/invoice/': typeof UserInvoiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/user'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/invoice'
    | '/user/dashboard'
    | '/user/invoice'
    | '/admin/account/$accountId'
    | '/admin/invoice/$invoiceId'
    | '/admin/invoice/new'
    | '/user/invoice/$invoiceId'
    | '/admin/account/'
    | '/admin/invoice/'
    | '/user/invoice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/user'
    | '/admin/dashboard'
    | '/user/dashboard'
    | '/admin/account/$accountId'
    | '/admin/invoice/$invoiceId'
    | '/admin/invoice/new'
    | '/user/invoice/$invoiceId'
    | '/admin/account'
    | '/admin/invoice'
    | '/user/invoice'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/user'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/invoice'
    | '/user/dashboard'
    | '/user/invoice'
    | '/admin/account/$accountId'
    | '/admin/invoice/$invoiceId'
    | '/admin/invoice/new'
    | '/user/invoice/$invoiceId'
    | '/admin/account/'
    | '/admin/invoice/'
    | '/user/invoice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/invoice': {
      id: '/user/invoice'
      path: '/invoice'
      fullPath: '/user/invoice'
      preLoaderRoute: typeof UserInvoiceRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/invoice': {
      id: '/admin/invoice'
      path: '/invoice'
      fullPath: '/admin/invoice'
      preLoaderRoute: typeof AdminInvoiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/invoice/': {
      id: '/user/invoice/'
      path: '/'
      fullPath: '/user/invoice/'
      preLoaderRoute: typeof UserInvoiceIndexRouteImport
      parentRoute: typeof UserInvoiceRoute
    }
    '/admin/invoice/': {
      id: '/admin/invoice/'
      path: '/'
      fullPath: '/admin/invoice/'
      preLoaderRoute: typeof AdminInvoiceIndexRouteImport
      parentRoute: typeof AdminInvoiceRoute
    }
    '/admin/account/': {
      id: '/admin/account/'
      path: '/'
      fullPath: '/admin/account/'
      preLoaderRoute: typeof AdminAccountIndexRouteImport
      parentRoute: typeof AdminAccountRoute
    }
    '/user/invoice/$invoiceId': {
      id: '/user/invoice/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/user/invoice/$invoiceId'
      preLoaderRoute: typeof UserInvoiceInvoiceIdRouteImport
      parentRoute: typeof UserInvoiceRoute
    }
    '/admin/invoice/new': {
      id: '/admin/invoice/new'
      path: '/new'
      fullPath: '/admin/invoice/new'
      preLoaderRoute: typeof AdminInvoiceNewRouteImport
      parentRoute: typeof AdminInvoiceRoute
    }
    '/admin/invoice/$invoiceId': {
      id: '/admin/invoice/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/admin/invoice/$invoiceId'
      preLoaderRoute: typeof AdminInvoiceInvoiceIdRouteImport
      parentRoute: typeof AdminInvoiceRoute
    }
    '/admin/account/$accountId': {
      id: '/admin/account/$accountId'
      path: '/$accountId'
      fullPath: '/admin/account/$accountId'
      preLoaderRoute: typeof AdminAccountAccountIdRouteImport
      parentRoute: typeof AdminAccountRoute
    }
  }
}

interface AdminAccountRouteChildren {
  AdminAccountAccountIdRoute: typeof AdminAccountAccountIdRoute
  AdminAccountIndexRoute: typeof AdminAccountIndexRoute
}

const AdminAccountRouteChildren: AdminAccountRouteChildren = {
  AdminAccountAccountIdRoute: AdminAccountAccountIdRoute,
  AdminAccountIndexRoute: AdminAccountIndexRoute,
}

const AdminAccountRouteWithChildren = AdminAccountRoute._addFileChildren(
  AdminAccountRouteChildren,
)

interface AdminInvoiceRouteChildren {
  AdminInvoiceInvoiceIdRoute: typeof AdminInvoiceInvoiceIdRoute
  AdminInvoiceNewRoute: typeof AdminInvoiceNewRoute
  AdminInvoiceIndexRoute: typeof AdminInvoiceIndexRoute
}

const AdminInvoiceRouteChildren: AdminInvoiceRouteChildren = {
  AdminInvoiceInvoiceIdRoute: AdminInvoiceInvoiceIdRoute,
  AdminInvoiceNewRoute: AdminInvoiceNewRoute,
  AdminInvoiceIndexRoute: AdminInvoiceIndexRoute,
}

const AdminInvoiceRouteWithChildren = AdminInvoiceRoute._addFileChildren(
  AdminInvoiceRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInvoiceRoute: typeof AdminInvoiceRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInvoiceRoute: AdminInvoiceRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserInvoiceRouteChildren {
  UserInvoiceInvoiceIdRoute: typeof UserInvoiceInvoiceIdRoute
  UserInvoiceIndexRoute: typeof UserInvoiceIndexRoute
}

const UserInvoiceRouteChildren: UserInvoiceRouteChildren = {
  UserInvoiceInvoiceIdRoute: UserInvoiceInvoiceIdRoute,
  UserInvoiceIndexRoute: UserInvoiceIndexRoute,
}

const UserInvoiceRouteWithChildren = UserInvoiceRoute._addFileChildren(
  UserInvoiceRouteChildren,
)

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserInvoiceRoute: typeof UserInvoiceRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserInvoiceRoute: UserInvoiceRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
